module Mirzam
  VERSION: String
  def self.render: (title: String, ?author: String?, ?date: String?, ?tags: Array[String], ?description: String?, ?accent: String?, ?template: Symbol, ?theme: untyped, ?width: Integer, ?height: Integer, ?font_dir: String?) -> String
  class Error < StandardError
  end
  class Renderer
    def render: (untyped source, ?template: untyped) -> String
  end
end
